version: '3'
services:
  tg_proxy:
    build: ./app
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./app/:/usr/src/app/
    environment:
      - TG_TOKEN=${TG_TOKEN}
    command: uvicorn fastapi_proxy:app --host 0.0.0.0 --port 5000 --reload